### ISSUE TITLE
Incorrect version in documentation (V2?)

### ISSUE THREAD

**Issue by pkrisko** [contentful-userland/contentful-action#6]
I don't see a V2 version anywhere, and the version in the README workflow file example is inconsistent with the examples respository.

**Comment by pkrisko** [comment]
I'm unable to raise a pull request, but I have a branch locally I can raise if you all give me permission.

**Comment by pixelass** [comment]
Thank you for reporting
The readme was migrated from a different action. There is only v1 right now. I'll fix it in the docs.
